all: README.pdf README.latex.pdf

README.pdf: README.md img/ConfigShell_modules.drawio.png
	./createREADME.pdf.sh

README.latex.pdf: README.latex.md img/ConfigShell_modules.drawio.png
	md2pdf README.latex.md


