#!/usr/bin/env ruby
VERSION="v2.1.24"
args    = ARGV.join(" ")
count   = -1
outarr  = Array.new()
# read lines beginning with BEGIN CERTIFICATE and the following into an outarr
IO.foreach(args) do | name |
    if name.include? "----BEGIN CERTIFICATE"
        count += 1
    end
    outarr[count] = outarr[count].to_s + name if count >= 0
end
print "############################################################\n"
print "Certificate: ", args, "\n"
print "Number of certificates (#{VERSION}): ", count+1, "\n"
print "============================================================\n"
(count+1).times do |val|
    IO.popen("openssl x509 -subject -email -issuer -dates -sha256 -serial -noout -ext 'subjectAltName,authorityKeyIdentifier,subjectKeyIdentifier' 2>/dev/null", "w+") do |proc|
         proc.write(outarr[val])
         proc.close_write
         puts "--------------------------------------------------------------" if val > 0

         proc.readlines.each { |x|
            if x.length > 1
               print (x.to_s.gsub("\n", ""))
               print ("\n") if not [ "Identifier", "Alternative Name" ].any?{ |s| x.include? s }
            end
         }
    end
end

