# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
#[character] # The name of the module we are configuring is 'character'
#success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# format = '$all'

[status]
disabled = false

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = '🅰 '

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'

# 250605
# node showed timeout problems, 
#  timeouts on node command #5707
#  https://github.com/starship/starship/discussions/5707
# doc for Node.js
#  https://starship.rs/config/#node-js
# circumvented by below
[nodejs]
version_format = ''
# disabled = true
